services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liberiaworks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d liberiaworks']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - '5020:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  # pgadmin_data:
